<a href="https://colab.research.google.com/github/prabhhav/JupyterNotebooks/blob/main/Custom_Image_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import os
import cv2
import numpy as np
from zipfile import ZipFile
from tqdm import tqdm

In [8]:
!ls

ezyzip	ezyzip.zip  sample_data


In [9]:
os.listdir()

['.config', 'ezyzip.zip', 'ezyzip', '.ipynb_checkpoints', 'sample_data']

In [10]:
import shutil
if(os.path.isdir("ezyzip")):
  shutil.rmtree("ezyzip", ignore_errors=False, onerror=None)

In [16]:
os.path.isdir("ezyzip")

True

In [17]:
root_path = "ezyzip.zip"

In [18]:
def uncompress_features_labels(dir,name):
  if(os.path.isdir("ezyzip")):
    print("Data Extracted")
  else:
     with ZipFile(dir) as zipf:
       zipf.extractall(name)


In [19]:
uncompress_features_labels(root_path,'ezyzip')

Data Extracted


In [20]:
DATADIR = "ezyzip/Data"
CATEGORIES = os.listdir("ezyzip/Data")
IMG_SIZE = 224

In [21]:
os.listdir(DATADIR)

['Plane', 'Cruise']

In [22]:
CATEGORIES

['Plane', 'Cruise']

Create Training Data

In [23]:
training_data = []

for category in CATEGORIES:
  print(category)
  path = os.path.join(DATADIR, category)
  print(path)
  class_num = CATEGORIES.index(category)
  print(class_num)

  for img in tqdm(os.listdir(path)):
    print(img)
    img_path = os.path.join(path,img)
    img_array = cv2.imread(img_path, cv2.COLOR_BGR2RGB)
    new_image = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    training_data.append([new_image, class_num])

 13%|█▎        | 2/15 [00:00<00:00, 16.91it/s]

Plane
ezyzip/Data/Plane
0
Plane4.jfif
Plane11.jfif
Plane3.jfif
Plane1.jfif
Plane5.jfif
Plane15.jfif
Plane10.jfif


 67%|██████▋   | 10/15 [00:00<00:00, 18.88it/s]

Plane8.jfif
Plane9.jfif
Plane2.jpg
Plane14.jfif


 87%|████████▋ | 13/15 [00:00<00:00, 20.23it/s]

Plane13.jfif
Plane12.jfif
plane7.jfif


  0%|          | 0/15 [00:00<?, ?it/s]

Plane6.jfif
Cruise
ezyzip/Data/Cruise
1
ship12.jfif
ship5.jfif
ship14.jfif
ship4.jfif
ship3.jfif
ship10.jfif


 60%|██████    | 9/15 [00:00<00:00, 32.56it/s]

ship13.jfif
ship6.jfif
ship2.jfif
ship9.jfif
ship.jfif
ship11.jfif
ship7.jfif


100%|██████████| 15/15 [00:00<00:00, 34.63it/s]

ship8.jfif
ship15.jfif


In [24]:
len(training_data)

30

In [25]:
training_data[0][0]

array([[[200, 144, 105],
        [202, 145, 106],
        [201, 146, 107],
        ...,
        [177, 117,  81],
        [175, 117,  82],
        [172, 113,  79]],

       [[203, 148, 111],
        [205, 147, 111],
        [206, 150, 114],
        ...,
        [183, 122,  89],
        [178, 121,  83],
        [176, 117,  85]],

       [[208, 152, 117],
        [202, 149, 112],
        [203, 151, 113],
        ...,
        [176, 120,  84],
        [177, 121,  86],
        [176, 120,  85]],

       ...,

       [[164, 159, 160],
        [162, 157, 158],
        [164, 159, 160],
        ...,
        [123, 104,  99],
        [121, 102,  97],
        [120, 104,  97]],

       [[164, 159, 160],
        [163, 158, 159],
        [162, 157, 158],
        ...,
        [118, 100,  93],
        [120, 101,  96],
        [122, 104,  97]],

       [[160, 155, 156],
        [161, 156, 157],
        [160, 155, 156],
        ...,
        [122, 103,  98],
        [120, 101,  96],
        [121, 103, 100]]

In [26]:
training_data[0][0].shape

(224, 224, 3)

Shuffle the data or else the order of the image may affect the performance of the network

Basic methods for training to train a model with this dataset you will want the data
* To be well shuffled
* To be batched 
* Batches to be available as soon as possible

In [27]:
# b4 shuffle 
for sample in training_data[:10]:
  print(sample[1])

0
0
0
0
0
0
0
0
0
0


In [28]:
import random
random.shuffle(training_data)

In [29]:
images = []
labels = []

for features,label in training_data:
  images.append(features)
  labels.append(label)

In [30]:
labels

[1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1]

In [31]:
# input
X = np.array(images)
X = X/255

# output
y = np.array(labels)

In [32]:
X.shape

(30, 224, 224, 3)

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)


In [34]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(24, 224, 224, 3)
(6, 224, 224, 3)
(24,)
(6,)


In [35]:
print(y_train)
print(y_test)

[0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 1]
[0 1 1 1 0 0]


In [36]:
import tensorflow as tf
from keras.layers import Dense
from keras.layers import Dropout
from keras import regularizers
from keras.optimizers import Adam


In [37]:
import tensorflow.keras.layers as layers
from keras.models import Sequential

CNN

In [38]:
cnn_model = tf.keras.Sequential()

cnn_model.add(layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape=(IMG_SIZE,IMG_SIZE,3)))
cnn_model.add(layers.MaxPooling2D((2,2)))

cnn_model.add(layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu'))
cnn_model.add(layers.MaxPooling2D((2,2)))


cnn_model.add(layers.Conv2D(filters=128, kernel_size=(3,3), activation='relu'))

cnn_model.add(layers.Flatten())

cnn_model.add(layers.Dense(units=128, activation='relu'))

cnn_model.add(layers.Dense(units=len(CATEGORIES), activation='softmax'))


In [39]:
cnn_model.compile(optimizer="adam", loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [67]:

#cnn_model.compile(loss='mean_squared_error',  optimizer=tf.keras.optimizers.Adam(0.1))

In [40]:
history = cnn_model.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test))

Epoch 1/20
1/1 [==============================] - 4s 4s/step - loss: 0.6923 - accuracy: 0.4583 - val_loss: 2.7776 - val_accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 3s 3s/step - loss: 0.7000 - accuracy: 0.7083 - val_loss: 29.7720 - val_accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 3s 3s/step - loss: 27.4646 - accuracy: 0.5000 - val_loss: 10.0769 - val_accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 2s 2s/step - loss: 8.9817 - accuracy: 0.5000 - val_loss: 0.5728 - val_accuracy: 0.8333
Epoch 5/20
1/1 [==============================] - 3s 3s/step - loss: 0.3693 - accuracy: 0.9167 - val_loss: 2.3738 - val_accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 2s 2s/step - loss: 1.2639 - accuracy: 0.5000 - val_loss: 1.1794 - val_accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 2s 2s/step - loss: 0.6375 - accuracy: 0.5833 - val_loss: 0.5541 - val_accuracy: 1.0000
Epoch 8/20
1/1 [======================

In [48]:
cnn_model.predict(X_test)

array([[5.4696828e-01, 4.5303172e-01],
       [1.3006508e-03, 9.9869931e-01],
       [7.1643235e-06, 9.9999285e-01],
       [3.5267405e-02, 9.6473253e-01],
       [4.9525273e-01, 5.0474727e-01],
       [9.8153704e-01, 1.8463010e-02]], dtype=float32)

In [47]:
y_hat_test = np.argmax(cnn_model.predict(X_test), axis=-1)

In [42]:
y_test

array([0, 1, 1, 1, 0, 0])

In [44]:
y_hat_test

5

In [45]:
y_hat_train = cnn_model.predict(X_train)
print(y_train)
print(np.argmax(y_hat_train, axis=-1))

[0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 1]
[0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 1]


In [49]:
from sklearn.metrics import classification_report, confusion_matrix

print('Confusion Matrix')
print(confusion_matrix(y_test, y_hat_test))
print('Classification Report')
print(classification_report(y_test, y_hat_test, target_names=CATEGORIES))

Confusion Matrix
[[2 1]
 [0 3]]
Classification Report
              precision    recall  f1-score   support

       Plane       1.00      0.67      0.80         3
      Cruise       0.75      1.00      0.86         3

    accuracy                           0.83         6
   macro avg       0.88      0.83      0.83         6
weighted avg       0.88      0.83      0.83         6

