<a href="https://colab.research.google.com/github/prabhhav/JupyterNotebooks/blob/main/RNN_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
train_data = {
  'good': True,
  'bad': False,
  'happy': True,
  'sad': False,
  'not good': False,
  'not bad': True,
  'not happy': False,
  'not sad': True,
  'very good': True,
  'very bad': False,
  'very happy': True,
  'very sad': False,
  'i am happy': True,
  'this is good': True,
  'i am bad': False,
  'this is bad': False,
  'i am sad': False,
  'this is sad': False,
  'i am not happy': False,
  'this is not good': False,
  'i am not bad': True,
  'this is not sad': True,
  'i am very happy': True,
  'this is very good': True,
  'i am very bad': False,
  'this is very sad': False,
  'this is very happy': True,
  'i am good not bad': True,
  'this is good not bad': True,
  'i am bad not good': False,
  'i am good and happy': True,
  'this is not good and not happy': False,
  'i am not at all good': False,
  'i am not at all bad': True,
  'i am not at all happy': False,
  'this is not at all sad': True,
  'this is not at all happy': False,
  'i am good right now': True,
  'i am bad right now': False,
  'this is bad right now': False,
  'i am sad right now': False,
  'i was good earlier': True,
  'i was happy earlier': True,
  'i was bad earlier': False,
  'i was sad earlier': False,
  'i am very bad right now': False,
  'this is very good right now': True,
  'this is very sad right now': False,
  'this was bad earlier': False,
  'this was very good earlier': True,
  'this was very bad earlier': False,
  'this was very happy earlier': True,
  'this was very sad earlier': False,
  'i was good and not bad earlier': True,
  'i was not good and not happy earlier': False,
  'i am not at all bad or sad right now': True,
  'i am not at all good or happy right now': False,
  'this was not happy and not good earlier': False,
}

test_data = {
  'this is happy': True,
  'i am good': True,
  'this is not happy': False,
  'i am not good': False,
  'this is not bad': True,
  'i am not sad': True,
  'i am very good': True,
  'this is very bad': False,
  'i am very sad': False,
  'this is bad not good': False,
  'this is good and happy': True,
  'i am not good and not happy': False,
  'i am not at all sad': True,
  'this is not at all good': False,
  'this is not at all bad': True,
  'this is good right now': True,
  'this is sad right now': False,
  'this is very bad right now': False,
  'this was good earlier': True,
  'i was not happy and not good earlier': False,
}

In [40]:
for text in train_data.keys():
  print(text.split(' '))

['good']
['bad']
['happy']
['sad']
['not', 'good']
['not', 'bad']
['not', 'happy']
['not', 'sad']
['very', 'good']
['very', 'bad']
['very', 'happy']
['very', 'sad']
['i', 'am', 'happy']
['this', 'is', 'good']
['i', 'am', 'bad']
['this', 'is', 'bad']
['i', 'am', 'sad']
['this', 'is', 'sad']
['i', 'am', 'not', 'happy']
['this', 'is', 'not', 'good']
['i', 'am', 'not', 'bad']
['this', 'is', 'not', 'sad']
['i', 'am', 'very', 'happy']
['this', 'is', 'very', 'good']
['i', 'am', 'very', 'bad']
['this', 'is', 'very', 'sad']
['this', 'is', 'very', 'happy']
['i', 'am', 'good', 'not', 'bad']
['this', 'is', 'good', 'not', 'bad']
['i', 'am', 'bad', 'not', 'good']
['i', 'am', 'good', 'and', 'happy']
['this', 'is', 'not', 'good', 'and', 'not', 'happy']
['i', 'am', 'not', 'at', 'all', 'good']
['i', 'am', 'not', 'at', 'all', 'bad']
['i', 'am', 'not', 'at', 'all', 'happy']
['this', 'is', 'not', 'at', 'all', 'sad']
['this', 'is', 'not', 'at', 'all', 'happy']
['i', 'am', 'good', 'right', 'now']
['i', 'am',

In [41]:
train_data.values()

dict_values([True, False, True, False, False, True, False, True, True, False, True, False, True, True, False, False, False, False, False, False, True, True, True, True, False, False, True, True, True, False, True, False, False, True, False, True, False, True, False, False, False, True, True, False, False, False, True, False, False, True, False, True, False, True, False, True, False, False])

In [42]:
vocab = list(set([w for text in train_data.keys() for w in text.split(' ')]))
vocab

['and',
 'bad',
 'am',
 'very',
 'sad',
 'not',
 'all',
 'is',
 'was',
 'or',
 'good',
 'at',
 'right',
 'i',
 'earlier',
 'happy',
 'this',
 'now']

In [43]:
vocab_size = len(vocab)
print('%d unique words found' % vocab_size)

18 unique words found


ModuleNotFoundError: ignored

assign an integer index

In [44]:
# Assign indices to each word
word_to_idx = { w: i for i, w in enumerate(vocab) }
idx_to_word = { i: w for i, w in enumerate(vocab) }

print(word_to_idx['good'])
print(idx_to_word)


10
{0: 'and', 1: 'bad', 2: 'am', 3: 'very', 4: 'sad', 5: 'not', 6: 'all', 7: 'is', 8: 'was', 9: 'or', 10: 'good', 11: 'at', 12: 'right', 13: 'i', 14: 'earlier', 15: 'happy', 16: 'this', 17: 'now'}


In [45]:
word_to_idx

{'all': 6,
 'am': 2,
 'and': 0,
 'at': 11,
 'bad': 1,
 'earlier': 14,
 'good': 10,
 'happy': 15,
 'i': 13,
 'is': 7,
 'not': 5,
 'now': 17,
 'or': 9,
 'right': 12,
 'sad': 4,
 'this': 16,
 'very': 3,
 'was': 8}

Finally, recall that each input x_ix to our RNN is a vector. We'll use one-hot vectors, which contain all zeros except for a single one. The "one" in each one-hot vector will be at the word's corresponding integer index

In [46]:
import numpy as np

In [19]:
def createInputs(text):


  inputs = []
  for w in text.split(' '):
    v = np.zeros((vocab_size, 1))
    v[word_to_idx[w]] = 1
    inputs.append(v)
    return inputs

In [20]:
createInputs("this is happy")

[array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]])]

The Forward Phase

In [21]:
import numpy as np
from numpy.random import randn

class RNN:

  def __init__(self, input_size, output_size, hidden_size=64):
    # Weights
    self.Whh = randn(hidden_size, hidden_size) / 1000
    self.Wxh = randn(hidden_size, input_size) / 1000
    self.Why = randn(output_size, hidden_size) / 1000

    # Biases
    self.bh = np.zeros((hidden_size, 1))
    self.by = np.zeros((output_size, 1))

  def forward(self, inputs):

    h = np.zeros((self.Whh.shape[0], 1))

    self.last_inputs = inputs
    self.last_hs = { 0: h }

    # Perform each step of the RNN
    for i, x in enumerate(inputs):
      h = np.tanh(self.Wxh @ x + self.Whh @ h + self.bh)
      self.last_hs[i + 1] = h

    # Compute the output
    y = self.Why @ h + self.by

    return y, h

  def backprop(self, d_y, learn_rate=2e-2):
    '''
    Perform a backward pass of the RNN.
    - d_y (dL/dy) has shape (output_size, 1).
    - learn_rate is a float.
    '''
    n = len(self.last_inputs)

    # Calculate dL/dWhy and dL/dby.
    d_Why = d_y @ self.last_hs[n].T
    d_by = d_y

    # Initialize dL/dWhh, dL/dWxh, and dL/dbh to zero.
    d_Whh = np.zeros(self.Whh.shape)
    d_Wxh = np.zeros(self.Wxh.shape)
    d_bh = np.zeros(self.bh.shape)

    # Calculate dL/dh for the last h.
    d_h = self.Why.T @ d_y

    # Backpropagate through time.
    for t in reversed(range(n)):
      # An intermediate value: dL/dh * (1 - h^2)
      temp = ((1 - self.last_hs[t + 1] ** 2) * d_h)

      # dL/db = dL/dh * (1 - h^2)
      d_bh += temp

      # dL/dWhh = dL/dh * (1 - h^2) * h_{t-1}
      d_Whh += temp @ self.last_hs[t].T

      # dL/dWxh = dL/dh * (1 - h^2) * x
      d_Wxh += temp @ self.last_inputs[t].T

      # Next dL/dh = dL/dh * (1 - h^2) * Whh
      d_h = self.Whh @ temp

    # Clip to prevent exploding gradients.
    for d in [d_Wxh, d_Whh, d_Why, d_bh, d_by]:
      np.clip(d, -1, 1, out=d)

    # Update weights and biases using gradient descent.
    self.Whh -= learn_rate * d_Whh
    self.Wxh -= learn_rate * d_Wxh
    self.Why -= learn_rate * d_Why
    self.bh -= learn_rate * d_bh
    self.by -= learn_rate * d_by






In [22]:
def softmax(xs):
  # Applies the Softmax Function to the input array.
  return np.exp(xs) / sum(np.exp(xs))

In [23]:
rnn = RNN(vocab_size, 2)

In [ ]:
## rnn._dict_

In [24]:
inputs = createInputs('i am very good')
out, h = rnn.forward(inputs)
probs = softmax(out)
print(probs)

[[0.50000402]
 [0.49999598]]


In [25]:
for val in rnn.last_hs.values():
  print(list(val))

[array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.])]
[array([-0.00074461]), array([6.41371251e-05]), array([0.00040274]), array([0.00230452]), array([-0.00099974]), array([-0.00060106]), array([0.00260351]), array([0.000

In [26]:
## after training execute this code
rnn.__dict__

{'Whh': array([[ 4.74653535e-04, -1.90932172e-03,  1.10688220e-03, ...,
         -1.38259978e-03,  9.02957215e-04,  3.00522172e-04],
        [ 2.81305218e-03, -2.81057857e-04, -1.92222546e-04, ...,
         -7.70713202e-04,  2.21915990e-04,  2.52733590e-04],
        [-1.03443336e-03,  8.86700203e-04, -1.16983978e-03, ...,
          5.71329399e-04, -1.07233568e-03,  9.06498427e-04],
        ...,
        [ 1.17822924e-03, -9.23294327e-04,  1.06683571e-03, ...,
          4.73385676e-04, -1.49107221e-04,  1.19287607e-03],
        [-7.40534692e-04,  6.95741568e-05,  1.00361633e-03, ...,
         -8.01239512e-04, -9.46138159e-04, -6.44806299e-04],
        [ 5.68316107e-04,  2.17559649e-03, -6.63493227e-04, ...,
          2.47010579e-04, -2.33431699e-03, -3.90704247e-04]]),
 'Why': array([[-8.40330357e-04,  4.48880582e-04, -5.34101882e-04,
          1.58068708e-03,  8.22736114e-05,  7.40587216e-04,
         -2.26726568e-04, -6.43059871e-04,  7.81025330e-04,
         -8.26868227e-04, -6.801878

In [27]:
for val in rnn.last_inputs:
  print(list(val))

[array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([1.]), array([0.]), array([0.]), array([0.]), array([0.])]


In [28]:
# Loop over each training example
for x, y in train_data.items():
  inputs = createInputs(x)
  target = int(y)

  # Forward
  out, _ = rnn.forward(inputs)
  probs = softmax(out)

  # Build dL/dy
  d_L_d_y = probs
  d_L_d_y[target] -= 1

  # Backward
  rnn.backprop(d_L_d_y)

adding few more lines to the previous training block

In [51]:
import random

def processData(data, backprop=True):
  '''
  Returns the RNN's loss and accuracy for the given data.
  - data is a dictionary mapping text to True or False.
  - backprop determines if the backward phase should be run.
  '''
  items = list(data.items())
  random.shuffle(items)

  loss = 0
  num_correct = 0

  for x, y in items:
    inputs = createInputs(x)
    target = int(y)

    # Forward
    out, _ = rnn.forward(inputs)
    probs = softmax(out)

    # Calculate loss / accuracy
    loss -= np.log(probs[target])
    num_correct += int(np.argmax(probs) == target)

    if backprop:
      # Build dL/dy
      d_L_d_y = probs
      d_L_d_y[target] -= 1

      # Backward
      rnn.backprop(d_L_d_y)

  return loss / len(data), num_correct / len(data)



In [52]:
# Training loop
for epoch in range(1000):
  train_loss, train_acc = processData(train_data)

  if epoch % 100 == 99:
    print('--- Epoch %d' % (epoch + 1))
    print('Train:\tLoss %.3f | Accuracy: %.3f' % (train_loss, train_acc))

    test_loss, test_acc = processData(test_data, backprop=False)
    print('Test:\tLoss %.3f | Accuracy: %.3f' % (test_loss, test_acc))

--- Epoch 100
Train:	Loss 0.691 | Accuracy: 0.552
Test:	Loss 0.701 | Accuracy: 0.500
--- Epoch 200
Train:	Loss 0.679 | Accuracy: 0.569
Test:	Loss 0.709 | Accuracy: 0.500
--- Epoch 300
Train:	Loss 0.663 | Accuracy: 0.586
Test:	Loss 0.694 | Accuracy: 0.500
--- Epoch 400
Train:	Loss 0.663 | Accuracy: 0.534
Test:	Loss 0.701 | Accuracy: 0.500
--- Epoch 500
Train:	Loss 0.660 | Accuracy: 0.552
Test:	Loss 0.703 | Accuracy: 0.500
--- Epoch 600
Train:	Loss 0.658 | Accuracy: 0.552
Test:	Loss 0.707 | Accuracy: 0.500
--- Epoch 700
Train:	Loss 0.658 | Accuracy: 0.517
Test:	Loss 0.702 | Accuracy: 0.500
--- Epoch 800
Train:	Loss 0.656 | Accuracy: 0.517
Test:	Loss 0.700 | Accuracy: 0.500
--- Epoch 900
Train:	Loss 0.655 | Accuracy: 0.569
Test:	Loss 0.699 | Accuracy: 0.500
--- Epoch 1000
Train:	Loss 0.655 | Accuracy: 0.534
Test:	Loss 0.707 | Accuracy: 0.500


In [53]:
inputs = createInputs('i am very good')
out, h = rnn.forward(inputs)
probs = softmax(out)
print(probs)

[[0.57764718]
 [0.42235282]]


In [54]:
ip = 'this is not bad'
inputs = createInputs(ip)
out, h = rnn.forward(inputs)
probs = softmax(out)
print(probs)

[[0.58697788]
 [0.41302212]]


In [55]:
ip = 'i am not at all happy'
inputs = createInputs(ip)
out, h = rnn.forward(inputs)
probs = softmax(out)
print(probs)

[[0.57764718]
 [0.42235282]]
